#!/usr/bin/env python3
"""Generate `ein.rs/crates/ein-core/src/printable.rs` — CPython's
`Py_UNICODE_ISPRINTABLE`, as a table ein.rs can binary-search.

`repr()` of a `str` escapes every non-printable character, and "printable"
in CPython means *not* in general category `Cc`/`Cf`/`Cs`/`Co`/`Cn`/`Zl`/
`Zp`/`Zs` — with ASCII space as the one exception. Rust's standard library
exposes `is_control()` (only `Cc`), so the rest has to come from a table, and
the table has to be **the oracle's**: parity is against whatever Unicode
version CPython was built with, not against whatever version `rustc` embeds.

Regenerate after a CPython upgrade — `ein-core`'s differential test against
`utils/py_oracle.py` is what tells you it is stale.

    python3 utils/gen_unicode_printable.py
"""
from __future__ import annotations

import unicodedata
from pathlib import Path

NON_PRINTABLE = {"Cc", "Cf", "Cs", "Co", "Cn", "Zl", "Zp", "Zs"}
OUT = Path(__file__).resolve().parent.parent / "ein.rs/crates/ein-core/src/printable.rs"


def non_printable(cp: int) -> bool:
    # CPython: `if (ch == ' ') return 1;` before the category test.
    return cp != 0x20 and unicodedata.category(chr(cp)) in NON_PRINTABLE


def ranges() -> list[tuple[int, int]]:
    out: list[tuple[int, int]] = []
    start: int | None = None
    for cp in range(0x110000):
        if non_printable(cp):
            if start is None:
                start = cp
        elif start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, 0x10FFFF))
    return out


def main() -> int:
    rs = ranges()
    body = "\n".join(f"    (0x{lo:04X}, 0x{hi:04X})," for lo, hi in rs)
    OUT.write_text(f'''//! CPython's `Py_UNICODE_ISPRINTABLE`, as a table.
//!
//! **Generated by `utils/gen_unicode_printable.py` — do not edit.**
//! Unicode {unicodedata.unidata_version}, as CPython sees it.
//!
//! `repr()` escapes every non-printable character, where non-printable means
//! general category `Cc`/`Cf`/`Cs`/`Co`/`Cn`/`Zl`/`Zp`/`Zs` — ASCII space
//! excepted. `rustc` embeds its own Unicode tables and exposes only
//! `is_control()`, so the categories that matter come from the *oracle's*
//! Unicode version instead: parity is with CPython, not with the standard
//! library that happens to be linked.

/// Sorted, non-overlapping ranges of non-printable code points.
const NON_PRINTABLE: [(u32, u32); {len(rs)}] = [
{body}
];

/// CPython's `Py_UNICODE_ISPRINTABLE(ch)`.
pub fn is_printable(ch: char) -> bool {{
    let cp = ch as u32;
    NON_PRINTABLE
        .binary_search_by(|&(lo, hi)| {{
            if cp < lo {{
                std::cmp::Ordering::Greater
            }} else if cp > hi {{
                std::cmp::Ordering::Less
            }} else {{
                std::cmp::Ordering::Equal
            }}
        }})
        .is_err()
}}

#[cfg(test)]
mod tests {{
    use super::is_printable;

    #[test]
    fn the_categories_cpython_escapes() {{
        // Printable: ASCII space is the documented exception, and ordinary
        // letters and emoji are printable whatever their width.
        for ch in [' ', 'a', 'Å', '😀', '中'] {{
            assert!(is_printable(ch), "{{ch:?}}");
        }}
        // Non-printable: Cc, Zs (NBSP), Cf (zero-width space), Zl, Zp, Co
        // (private use), Cn (unassigned).
        for ch in [
            '\\u{{0}}', '\\u{{1f}}', '\\u{{7f}}', '\\u{{a0}}', '\\u{{200b}}',
            '\\u{{2028}}', '\\u{{2029}}', '\\u{{e000}}', '\\u{{0378}}',
        ] {{
            assert!(!is_printable(ch), "{{ch:?}}");
        }}
    }}
}}
''')
    print(f"{OUT}: {len(rs)} ranges, Unicode {unicodedata.unidata_version}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
